import { Departamento } from '../products';
export const departamentosQuerySet: Departamento[ ] = [
    { nombre: "Clothing", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "http://cdn.playbuzz.com/cdn/02dad71a-73d0-46ac-80ec-b2555f689d34/0e83b243-b5fc-4d89-93e3-c4ff4dd47763.jpg"},
    { nombre: "Electronics", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "https://cdn2.cnet.com/img/C3RPtt8a_n1be4azT8jokd9vhsM=/1600x900/2016/07/21/d90577a0-8dc3-426a-889f-b3c29bbc9b17/4-laptops-dan-02.jpg"},
    { nombre: "Music", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "http://visitbreckenridge.com/wp-content/uploads/2015/08/toys.jpg"},    
    { nombre: "Garden", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar." , hero: "http://thumbs.media.smithsonianmag.com//filer/4e/f8/4ef87b4d-18fa-48a1-b8ca-865bb065c928/mw_poison_garden_tunnel.jpg__1072x0_q85_upscale.jpg"},    
    { nombre: "Grocery", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "http://www.organizedtransitionsllc.com/wp-content/uploads/2016/07/Food-Groceyr.jpg"},    
    { nombre: "Home", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "https://lynsfurniture.net/wp-content/uploads/2016/10/6-furniture-decorating-ideas-for-your-home-1.jpg"},
    { nombre: "Industrial", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "http://eup.cdf.udc.es/bild/fotos/la-produccic3b3n-industrial-india-crece-al-51.jpg"},
    { nombre: "Jewelery", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "http://cdn.paper4pc.com/images/diamonds-diamond-jewelery-bokeh-bling-abstraction-abstract-sparkle-wallpaper-3.jpg"},    
    { nombre: "Kids", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "https://s-media-cache-ak0.pinimg.com/originals/d3/c2/68/d3c268f8ce6e7dbac47dea5770a77544.jpg"}, 
    { nombre: "Movies", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "http://baltimoresportsandlife.com/wp-content/uploads/2016/07/Movies.jpg"},   
    { nombre: "Shoes", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "https://m.media-amazon.com/images/G/01/6pm/landing/coop/shoes/170201COOP/1._V534799631_.jpg"},
    { nombre: "Tools", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "https://www.clearpointstrategy.com/wp-content/uploads/2015/03/Reporting-Tools-Software-The-4-Most-Crucial-Aspects.jpg"},
    { nombre: "Toys", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet, magna in aliquam volutpat, felis purus suscipit urna, rutrum gravida diam felis ut enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque sagittis eros id ornare dapibus. Vivamus ipsum nunc, vestibulum sed luctus in, euismod et magna. Vivamus porttitor dignissim mauris non pulvinar. " , hero: "http://visitbreckenridge.com/wp-content/uploads/2015/08/toys.jpg"},  
];